### ISSUE TITLE
[DISCUSSION] 검색창 디자인 및 마커 마우스 이벤트 디자인 논의

### ISSUE THREAD

**Issue by kyeongjeong** [kyeongjeong/Seoul_amateur_orchestra_club#11]
## 검색창 디자인에 관한 논의
초기 화면구성도에는 검색창 내부에 돋보기 아이콘을 넣어서
검색어 입력 후 검색 아이콘을 누르면 검색 결과 목록이 뜨는 방식으로 하는 것으로 디자인되어 있습니다.
하지만 검색어 입력 후 아이콘을 눌러야만 결과가 뜨는 것이 불편하다고 생각되어,
차라리 아이콘을 없애고 검색어를 입력할 때마다 바로바로 결과가 뜨게끔 구현하는 게 낫다고 생각해서 그렇게 구현했는데, 다들 어떻게 생각하시나요?
![image](https://github.com/user-attachments/assets/23d2a4de-b273-4015-9edb-23e4642c00e2)
![image](https://github.com/user-attachments/assets/cb1e88b0-86ef-42ed-8d23-65504cfcd3c9)

## 마커 마우스 이벤트 창 통일에 대한 논의
원래는 orchestraClub 페이지는 마커에 마우스를 올려도 아무런 이벤트가 발생하지 않지만, 그렇게 되면 동아리를 구분하는 데 있어 불편함이 발생하기에 임의로 이벤트창을 생성했습니다.
그런데 이 마커 마우스 이벤트 창을 classic concert 화면과 굳이 통일해야 할까요?
classic concert 화면은 지도가 주를 이루기에 마커 클릭 시 나오는 이벤트창(사진+동아리명+주소 등)에 정보가 많아도 상관 없지만, 
orchestra club 페이지는 구성 요소가 많기에 이벤트창이 복잡하면 안 될 것 같아서 우선 동아리명과 소속대학명만 작게 뜨도록 이벤트창을 구성했습니다.
그러나 웹페이지의 전체적인 통일성을 위해서 통일을 하는 것이 나을까요?
![image](https://github.com/user-attachments/assets/938c5b20-d953-4a7e-8aaf-a91d3b273938)

**Comment by ohyeong** [comment]
## 검색창 디자인에 관한 논의
 넵. 저도 검색어를 입력할 때마다 바로바로 결과가 뜨는게 기능적으로도 디자인적으로도 나아 보입니다. 이대로 하는게 좋을 것 같습니다.

## 마커 마우스 이벤트 창 통일에 대한 논의
 임의로 이벤트창을 생성은 없는것보다 훨씬 좋아 보입니다. 
그리고 이벤트 창은 굳이 classic concert 화면과 통일을 하지 않아도 될 것 같습니다.
classic concert 화면은 지도의 위치를 조절하면서 볼 수 있기 때문에 이벤트 창이 커도 상관이 없는데
경정님이 맡으신 페이지의 지도는 그냥 이미지기 때문에 지도 api에 뜨는 이벤트 창처럼 수정하게 되면 말씀하신대로 복잡해 보일것 같습니다.
