### ISSUE TITLE
[FEATURE] 헤더 통일, 사이드 배너 완성

### ISSUE THREAD

**Issue by dokyung17** [kyeongjeong/Seoul_amateur_orchestra_club#15]
## 어떤 기능인가요?
> 헤더 다른 페이지와 같은 디자인으로 통일
사이드 배너 사이즈 변경,  스크롤에 따라 섹션 색상 변경 

## 작업 상세 내용
- [ ] 헤더 사이즈, 폰트 조정
- [ ] 사이드 배너 원, 밑줄 사이즈 변경
- [ ] 사이드 배너 색상 활성화

**Comment by ohyeong** [comment]
## 수정해야 할 부분
- 처음에 페이지를 열자마자 바로 왼쪽 사이드 배너 중 '정보' 부분이 노란색으로 변해야 하는데 변하지 않아서 수정이 필요해 보입니다.
- 처음에 페이지를 열었을 때 바로 '정보'를 누르면 변화가 없습니다. 다른 배너를 누르고 다시 '정보' 버튼을 눌러야 색 변화가 생겨서 이 부분 수정 부탁드립니다.
- 사이드 배너 버튼을 눌렀을 때 설명 화면의 시작 부분이 여백이 너무 많습니다. 여백은 조금만 주고 설명이 보이도록 해야 할것 같습니다.
- 구분선과 제목 사이의 간격이 우리가 정한 양식대로 안된것 같습니다. 위쪽 내용과 구분선 사이의 거리가 70px, 구분선과 제목 사이의 간격이 40px로 해야합니다. 크기 확인 다시 부탁드립니다.
- 헤더에 'Classic Concert' 메뉴를 누르면 현재 페이지가 아니라 제가 맡은 페이지로 넘어가야 합니다. 이 부분 url 다시 확인 부탁드립니다.
