### ISSUE TITLE
[FEATURE] header 구현, 지도 구현, 예시 사진 추가

### ISSUE THREAD

**Issue by ohyeong** [kyeongjeong/Seoul_amateur_orchestra_club#2]
## 어떤 기능인가요?
> 모든 구성원들이 쓰는 hedaer를 구현하였으며, 위치 정보를 포함하는 지도가 화면에 뜨도록 구현하였음.

## 작업 상세 내용
- [ ] 로고 및 카테고리를 포함한 header 구현
- [ ] 예시 사진 추가
- [ ] 지도 API 사용하여 마커를 눌렀을 때 상세 정보를 포함하는 팝업화면 구현

## 참고할만한 자료(선택)
https://apis.map.kakao.com/
> 여기서 지도 API 발급받음

https://apis.map.kakao.com/web/guide/
https://apis.map.kakao.com/web/sample/
> 공식 홈페이지 통해 지도 API 구현 및 프로젝트에 맞게 꾸미는 걸 참고함.

**Comment by kyeongjeong** [comment]
API 키 사용에 관한 부분을 노션에 함께 첨부해주시면 좋을 것 같습니다...!!
노션에 적힌 키를 사용했는데 지도 로딩이 안되네요

**Comment by ohyeong** [comment]
혹시 프로그램 실행시킬 때 그냥 html 파일만 열어보셨나요??
API 키를 사용했기 때문에 VSCode같은 경우는 Live Server를 사용하여 프로그램을 실행시켜야 합니다.
또한, 제가 5500포트로 주소를 등록했기 때문에 5500포트로 실행시키면 될것 같습니다.
이 부분은 노션에도 추가하겠습니다.
