### ISSUE TITLE
[DISCUSSION] 곡 추천 중 발생하는 예외사항에 대한 논의

### ISSUE THREAD

**Issue by kyeongjeong** [kyeongjeong/Seoul_amateur_orchestra_club#26]
## 옵션을 아무것도 선택하지 않았을 경우
현재는 경고창을 띄워 사용자가 적어도 한 개 이상의 곡을 선택하게끔 하고 있습니다.
그러나 조건 없이 곡을 추천 받고 싶어할 경우도 있을 것 같은데, 
옵션 선택을 안하면 차라리 그냥 전체 곡에서 랜덤하게 추천을 하는 것이 나을까요?

![image](https://github.com/user-attachments/assets/f0ea07ea-2acd-4010-b754-5337553bb40d)

## 해당 조건에 맞는 곡이 없는 경우
현재는 no result로 간단하게 예외처리 중입니다.
이런 경우도 마찬가지로, "해당 조건에 맞는 곡은 없으나 대신 이런 곡은 어떨까요?" 이런 뉘앙스를 주면서 다른 곡을 추천하는 게 나을까요?
아니면 이대로 그냥 두는 것이 맞을까요?

![image](https://github.com/user-attachments/assets/518220c8-d869-4d31-997d-87fc36ecd672)

**Comment by Hagyeong13** [comment]
1. 옵션을 선택하지 않고 추천을 눌렀을 경우엔, 추천을 받고는 싶으나 조건들을 제대로 알고 있지 못한 사용자를 위해서 전체 곡에서 랜덤으로 추천하는 것이 좋을 것 같습니다. 

2. 해당 곡은 없지만 이런 곡은 어떤지 물어보며 유사한 곡을 추천하는 것이 좋을 것 같습니다.

**Comment by ohyeong** [comment]
1. 저는 굳이 추천을 할 필요가 없다고 생각합니다. 조건을 한 개 이상 넣은 뒤에 추천이 되는게 좋다고 생각이 듭니다. 애초에 검색을 하는 이유가 필터링을 위해서라고 생각이 드는데 랜덤적으로 뜨는 건 이와 맞지 않다고 생각이 들기 때문입니다.

2. 해당 조건에 맞는 곡이 없으니 다른 곡을 추천하는 것은 괜찮을 것 같습니다.

**Comment by dokyung17** [comment]
1. 옵션 선택하고 곡 추천을 해줄 때도 옵션에 해당하는 모든 곡을 한번에 보여주는게 아닌 하나씩 랜덤으로 곡을 추천하고 있으니까 옵션 안 넣고 검색했을 때도 랜덤으로 보여주는 것도 괜찮을 거 같습니다. 
2. 
3. 유사한 곡을 보여주려고 하면 어떤 부분에서 유사한지 적어야 될 거 같고, 이게 옵션에 따라 유사한 곡이 달라질 수 있다고 생각해서 no result 로 내비두는 것도 괜찮을 거 같습니다.
