### ISSUE TITLE
[DISCUSSION] 세부동아리 소개 페이지에 대한 논의

### ISSUE THREAD

**Issue by Hagyeong13** [kyeongjeong/Seoul_amateur_orchestra_club#30]
## 연혁 검정 배경의 크기
현재는 연혁이 작성한 내용만큼 검정 배경으로 설정되게 해두었는데, 연혁의 내용이 이전 공연 소개 내용보다 작을 경우에 검정 배경의 크기를 이전 공연 소개 내용 만큼 늘리는 것이 좋을까요?

<img width="959" alt="늘린 ver" src="https://github.com/user-attachments/assets/39833814-8328-41a7-96fb-cfd21ff6793b">

## 연혁 버튼 시작 부분
스크롤 내비게이션의 연혁을 눌렀을 경우 이동하는 부분이 현재는 사진의 시작 부분에 고정되어 있는데, 소개 부분과 마찬가지로 70px 위에서부터 보일 수 있도록 하는게 좋을까요?
<img width="954" alt="사진부터 시작" src="https://github.com/user-attachments/assets/7e695d47-01b4-4f22-b42c-04f7f42844ef">
<img width="959" alt="70px 위" src="https://github.com/user-attachments/assets/0786b1a3-0762-467d-86b3-d07e0fba65f7">

**Comment by kyeongjeong** [comment]
1. 네 검정 부분을 공연 소개가 있는 만큼 늘리는 것이 더 좋아 보입니다.
2. 똑같이 마진을 70px 주는 게 일관성 있고 좋을 것 같습니다.

**Comment by ohyeong** [comment]
1. 넵 검정 배경의 크기를 이전 공연 소개 내용 만큼 늘리는 것이 더 좋을 것 같습니다.

2. 70px 위에서부터 보일 수 있도록 하는게 좋을 것 같습니다.

**Comment by dokyung17** [comment]
1. 늘리는게 괜찮을 것 같습니다. 
2.  70px 마진 주는게 좋을 것 같습니다.
