### ISSUE TITLE
[DISCUSSION] 연주회 정보 부족한 것에 대한 논의

### ISSUE THREAD

**Issue by dokyung17** [kyeongjeong/Seoul_amateur_orchestra_club#31]
## 정보 부족 경우
동아리에서 알려준 공연 정보가, 지휘자, 악장, 공연 시작 달만 알려주었을 때 포스터가 없어서 사진 처럼 게시됩니다. 이럴 경우에는 그대로 내버려두는게 괜찮을까요?
![image](https://github.com/user-attachments/assets/08445bfe-d49e-4e27-a0b1-be7c0564ec65)

그리고 몇몇 동아리는 소개, 지휘자 정보가 나와있어서 채워 넣을 수 있었는데 없는 곳은 그냥 섹션을 지워버렸습니다. 그러면서 사이드 배너의 동그라미 개수 또한 일관되지 않게 되었는데 소개, 지휘자 없는 동아리도 그냥 섹션 넣어서 사이드 배너에 유지 시켜는게 나을까요?

![image](https://github.com/user-attachments/assets/659430be-7949-44a8-a7c5-dff5f2d7d01f)![image](https://github.com/user-attachments/assets/5fc7d907-cfd4-4b5f-8a54-b6a307eb662c)![image](https://github.com/user-attachments/assets/6d17036a-d69e-4a79-ab37-4fdf7027ec91)

## 가독성 떨어짐 이슈
마지막으로 프로그램에 글이 너무 많아서 가독성이 떨어지는 거 같다고 느껴지는데 다른 분들 생각도 듣고 싶습니다. 
![image](https://github.com/user-attachments/assets/dfa54522-5e4d-455a-96c5-736056209d31)

**Comment by kyeongjeong** [comment]
1. 미정은 그대로 적어도 괜찮으나, 사진의 경우 수정이 필요할 듯 합니다. 대체 이미지(회색 no image 등)을 넣어야 할 것 같아요.
2. 넵 네비게이션에서도 빼는 게 좋을 것 같아 보입니다.
3. 저는 가독성은 괜찮다고 느껴서..

**Comment by Hagyeong13** [comment]
1. 미정은 그대로 유지하는 것이 좋을 것 같습니다.
2. 내비게이션은 눌렀을 때 해당 부분으로 이동하지 못하는 것보다 지우는 게 좋을 것 같습니다.
3. 문단을 시작하는 부분에 띄어쓰기를 하면 좋을 것 같습니다.

**Comment by ohyeong** [comment]
1. 포스터가 없는 공연은 대체 이미지를 만들어서 그 이미지로 대체해야 할 것 같습니다. 그대로 두면 뭔가 오류가 난 것처럼 보여서 뭔가라도 있으면 좋을 것 같습니다.

2. 없으면 없애는 것도 좋은 것 같습니다.

3. 저는 가독성이 그렇게 나쁘지는 않은 것 같은데 도경님께서 나쁘다고 느껴지시면 중요한 부분에 굵게 표시하는 것도 좋은 것 같습니다.
