### ISSUE TITLE
[DISCUSSION] 길찾기 기능에 관한 논의

### ISSUE THREAD

**Issue by ohyeong** [kyeongjeong/Seoul_amateur_orchestra_club#32]
## 검색 후 페이징 기능이 있어야 할까요?
현재 한페이지에 5개씩 볼 수 있고 페이징으로 넘기면서 볼 수 있게 되어 있는데 굳이 페이징까지 하면서 많은 장소를 보여줄 필요는 없어보입니다. 더 정확한 장소를 원한다면 정확하게 키워드를 작성하면 되는 거라 연관된 장소는 5개까지만 보여주는게 어떨까요?
![image](https://github.com/user-attachments/assets/0ef8ed48-3477-4415-8e4b-6b784e1b1ec9)

## 길찾기 후에 어떤 내용을 넣어야 할까요?
현재는 출발지에서 도착지까지 가는 경로와 가는 시간 정도만 뜨게 되어 있는데 다음 링크를 보시면 다양한 정보를 넣을 수 있습니다. 어떤 내용을 추가로 더 넣었으면 좋을까요?
https://developers.kakaomobility.com/docs/navi-api/directions/
![image](https://github.com/user-attachments/assets/4da3ae87-cc51-46a7-8eb1-0c52b1f0059b)
![image](https://github.com/user-attachments/assets/51383989-8680-44a6-9dde-88003822a328)

## 현재 UI 괜찮은가요?
길찾기 버튼 맨 밑에 있는거 괜찮은지, 출발지&도착지 검색이 좌우에 있는게 괜찮을까요? 의견 주시면 감사하겠습니다.
![image](https://github.com/user-attachments/assets/166a379f-60d5-4044-b00f-39d82307ee28)

**Comment by kyeongjeong** [comment]
1. 제 생각에도 페이징까진 필요 없을 것 같습니다. 5개 적당하고 괜찮네요
2. 추가적으로 현재 교통 상황도 알 수 있으면 좋을 것 같아요
3. 출발지와 도착지 검색 칸의 좌우를 조금 줄이고, 길찾기 버튼을 옆에 넣는 건 어떨까요?

**Comment by dokyung17** [comment]
1. 페이징 없이 5개만 보여주는게 더 괜찮을 것 같습니다.
2. 상세 도로 정보와 대안 경로 제공해주면 좋을 것 같습니다.
3.  길찾기 버튼이 밑 보다는 출발지, 도착지랑 같은 줄에 있으면 괜찮을 거 같습니다.

**Comment by Hagyeong13** [comment]
1. 원하는 곳이 나오지 않을 경우 더 자세히 입력하는게 좋다고 생각되어 페이징이 없어도 될 것 같습니다.
2. 총 거리와 예상 시간만 있어도 충분하다고 생각되나, 예상시간이 사진과 같이 소수점이 존재하는 것보다 정수의 값으로 나타나면 좋을 것 같습니다.
3. 길찾기 버튼이 출발지, 도착지와 같은 줄에 존재하게 하거나 같은 줄이 어려울 경우 크기를 키워 가운데나 오른쪽에 배치하는 게 좋을 것 같습니다.
