### ISSUE TITLE
[DISCUSSION] 세부동아리 소개 페이지에 대한 논의

### ISSUE THREAD

**Issue by Hagyeong13** [kyeongjeong/Seoul_amateur_orchestra_club#52]
## 인스타 링크 삽입 위치
![image](https://github.com/user-attachments/assets/fe820c9c-c1f0-4408-8ee1-9f13db69f05d)
인스타 링크를 삽입할 때, 소개글이 끝나고 연혁 시작하기 전에 링크를 삽입하는 것이 좋을까요? 다른 위치에 삽입하는 것이 좋을까요?

## 인스타 로고 삽입 디자인
![image](https://github.com/user-attachments/assets/e1244617-ede8-4b64-a42f-cad92de11102)
![image](https://github.com/user-attachments/assets/ca66fcd5-0d47-4c98-979a-c1d9b2f94952)
인스타 로고와 인스타 링크를 삽입하는 것이 좋을까요? 아니면 인스타 로고를 누를 경우에 인스타로 이동하는 것이 좋을까요? 아니면 이전 공연 영상 바로가기와 같이 화살표와 링크이동으로 삽입하는 것이 좋을까요?

**Comment by dokyung17** [comment]
인스타 로고가 있으면 좋을 거 같은데 링크 삽입할 때 instagra.com/uos_ccantabile 이렇게 말고 그냥 동아리 이름만 나오게 하면 좋을 거 같습니다. 
위치는 소개글 끝나고 연혁 칸 오른쪽 끝에 맞춰서 삽입하면 깔끔할 거 같습니다. 
![image](https://github.com/user-attachments/assets/3fc547d3-bf40-4df4-82bf-b14c0a3b1c73)
